---
  - name: Setup ansible docker plugin
    hosts: localhost
    become: yes
    tasks:
      - name: Install community.docker role
        command: ansible-galaxy install -r Configure-OpenPLC-Docker-Requirements.yaml
  
  - name: Install docker python library on openplc hosts
    hosts: openplc
    become: yes
    tasks:
      - name: Install pip3
        apt:
          name: python3-pip
          state: latest
      - name: Install with pip
        pip:
          name: docker



  - name: Setup and run docker image
    hosts: openplc
    become: yes
    tasks:
      - name: Build docker image
        community.docker.docker_image:
          name: openplc:v3
          build: 
            path: .
          source: build