---
  - name: Setup ansible docker plugin
    hosts: localhost
    become: yes
    tasks:
      - name: Install community.docker role
        command: ansible-galaxy install -r Configure-OpenPLC-Docker-Requirements.yaml

  - name: Setup and run docker image
    hosts: localhost
    become: yes
    tasks:
      - name: Build docker image
        community.docker.docker_image:
          name: openplc:v3
          build: 
            path: .
          source: build
          docker_host: "{{ groups['openplc'] | map('extract', hostvars, ['ansible_host']) | join(',')}}"